[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = ["python3.10 -m pip install --upgrade pip", "python3.10 -m pip install -r requirements.txt"]

[start]
cmd = "python3.10 discord_bot.py"
